mozilla/telemetry-streaming

src/main/scala/com/mozilla/telemetry/streaming/ErrorAggregator.scala

The kafka consumer has a setting that limits the maximum amount of data
per-partition that can be fetched from the server. This must be higher
than the maximum size of a ping, otherwise the job will raise an error.
The 8MB value was found empirically, we may have to further tune it in
the future.

Bug 1338495 - Increase maximum partition fetch size

---

src/main/scala/com/mozilla/telemetry/streaming/ErrorAggregator.scala

This is useful when we want to recover from an expected data loss.
Fixes #25

Add failOnDataLoss option to ErrorAggregator

---

src/main/scala/com/mozilla/telemetry/streaming/ErrorAggregator.scala

This is one of the metrics suggested by releng.
I will use it to test schema updates as per #19

Add SLOW_SCRIPT_PAGE_COUNT to ErrorAggregator stats

---

.travis.yml
build.sbt
scalastyle-config.xml
src/main/scala/com/mozilla/telemetry/pings/package.scala
src/main/scala/com/mozilla/telemetry/streaming/ErrorAggregator.scala
src/main/scala/com/mozilla/telemetry/timeseries/package.scala
src/test/scala/com/mozilla/telemetry/streaming/TestAggregator.scala
src/test/scala/com/mozilla/telemetry/streaming/TestPings.scala
src/test/scala/com/mozilla/telemetry/streaming/TestUtils.scala

This PR introduces a few case classes representing crash and main pings.
This classes are then used to extract ping data out of HekaMessages
Fixes #39

Add case classes representing crash and main pings.

---

src/main/scala/com/mozilla/telemetry/streaming/ErrorAggregator.scala
src/test/scala/com/mozilla/telemetry/streaming/TestAggregator.scala

This makes the dataset easier to interact with for downstream consumers.

Split window column into 2 timestamp columns

---

build.sbt
src/main/scala/com/mozilla/telemetry/streaming/ErrorAggregator.scala
src/test/scala/com/mozilla/telemetry/TestUtils.scala
src/test/scala/com/mozilla/telemetry/streaming/TestErrorAggregator.scala

This change adds the ability to cheaply compute user set cardinality
using hyperloglog.
HLL is used to both count the number of distinct users for each
aggegate and to measure the impact that a certain anomaly has on users,
e.g. how many users are affected by main crashes.

Add client_count-based statistics

---

src/main/scala/com/mozilla/telemetry/pings/package.scala
src/main/scala/com/mozilla/telemetry/streaming/ErrorAggregator.scala
src/test/scala/com/mozilla/telemetry/TestUtils.scala
src/test/scala/com/mozilla/telemetry/pings/TestPings.scala
src/test/scala/com/mozilla/telemetry/streaming/TestErrorAggregator.scala

Same as 8687e8e6b861f50f178bfa841bea64b09b00cd36, but this time for
session counts. I added client_id to the recipe for the session hll
to mitigate the risk of collisions.

Add session count-based statistics

---

src/main/scala/com/mozilla/telemetry/pings/package.scala
src/main/scala/com/mozilla/telemetry/streaming/ErrorAggregator.scala
src/test/scala/com/mozilla/telemetry/TestUtils.scala
src/test/scala/com/mozilla/telemetry/pings/TestPings.scala
src/test/scala/com/mozilla/telemetry/streaming/TestErrorAggregator.scala

This new dimension allows us to distinguish between new profiles, young
profiles, old profiles and so on. I arbitrarily decided that profiles
older than 60 days will all end up in the 60th bucket to avoid an
explosion of the number of aggregates.
I also increased the schema version as this change is not backward
compatible and it will require a data backfill.

Add new profile_age_days dimension

---

src/main/scala/com/mozilla/telemetry/streaming/ErrorAggregator.scala

This failed when reading the final parquet output

Remove duplicate client_count columns

---

src/main/scala/com/mozilla/telemetry/pings/package.scala
src/main/scala/com/mozilla/telemetry/streaming/ErrorAggregator.scala
src/test/scala/com/mozilla/telemetry/pings/TestPings.scala
src/test/scala/com/mozilla/telemetry/streaming/TestErrorAggregator.scala

We see over 9000 different os_versions a day. We really don't care
about all of those, so this will normalize them: e.g. instead of
"1.1.1-special-build", it will just get "1.1.1".
Fixes #75

Normalize os_version in error_aggregates

---

src/main/scala/com/mozilla/telemetry/pings/package.scala
src/main/scala/com/mozilla/telemetry/streaming/ErrorAggregator.scala
src/test/scala/com/mozilla/telemetry/streaming/TestErrorAggregator.scala

This will reduce the number of aggregates we generate, which should
speed up aggregation and reduce the size of the output parquet file.

Limit build ids to the last 6 months

---

src/main/scala/com/mozilla/telemetry/pings/package.scala
src/main/scala/com/mozilla/telemetry/streaming/ErrorAggregator.scala
src/test/scala/com/mozilla/telemetry/TestUtils.scala
src/test/scala/com/mozilla/telemetry/streaming/TestErrorAggregator.scala

This column will give more precise versioning information (e.g. 47.0b1 as
opposed to just 47.0). It should not increase the cardinality of the dataset,
as there should be a 1:1 mapping between it and buildId.

Add displayVersion to error aggregates table

---

build.sbt
project/plugins.sbt

- Moztelemetry add maven local repo to replace sonatype
- Add circleci build to automatically publish jar to local maven repo on commits to master (this will require extra setup on the github side)

[Bug 1375018] telemetry-streaming add maven local repo to replace sonatype

---

src/main/scala/com/mozilla/telemetry/streaming/ErrorAggregator.scala
src/main/scala/com/mozilla/telemetry/streaming/ExperimentsErrorAggregator.scala
src/test/scala/com/mozilla/telemetry/streaming/TestErrorAggregator.scala
src/test/scala/com/mozilla/telemetry/streaming/TestExperimentsErrorAggregator.scala

Spark distributes the objects at the beginning of the run. That
means that any updates to the object only occur on the master node.
This means previously, the schema didn't match between what
the master node expected and the slaves wrote.
This moves all those object variables to function arguments,
which are guaranteed to be evaluated at runtime, not distribution
time.

Bug 1414942 - Move object variables to function arguments

---

src/main/scala/com/mozilla/telemetry/streaming/ErrorAggregator.scala

It seemed to be unecessary, and was causing the job to fail.

Bug 1425861 - Remove optEncoder

---

src/main/scala/com/mozilla/telemetry/pings/package.scala
src/main/scala/com/mozilla/telemetry/streaming/ErrorAggregator.scala
src/test/scala/com/mozilla/telemetry/streaming/TestAggregator.scala
src/test/scala/com/mozilla/telemetry/streaming/TestUtils.scala

This is the "v1" branch with the code to add a displayVersion column backported. Hopefully we can deploy this successfully while waiting for a solution that allows us to deploy the rest of the functionality in the master branch, since it unblocks a pretty important relman use case -- using mission control to monitor beta rollouts.

Backport displayVersion schema addition

---

build.sbt
scalastyle-config.xml
src/test/scala/com/mozilla/telemetry/Kafka.scala
src/test/scala/com/mozilla/telemetry/TestUtils.scala
src/test/scala/com/mozilla/telemetry/pings/TestFocusEventPing.scala
src/test/scala/com/mozilla/telemetry/streaming/TestErrorAggregator.scala
src/test/scala/com/mozilla/telemetry/streaming/TestEventsToAmplitude.scala
src/test/scala/com/mozilla/telemetry/streaming/TestExperimentsErrorAggregator.scala

This enables Scalastyle checks for tests. Also, some small refactors were needed so all tests conform to the rules.

Refactor tests to conform with Scalastyle rules, enable Scalastyle in test scope on CI

---

.travis.yml
README.md
docker_setup.sh
runtests.sh
src/main/scala/com/mozilla/telemetry/streaming/EventsToAmplitude.scala
src/test/scala/com/mozilla/telemetry/streaming/TestErrorAggregator.scala
src/test/scala/com/mozilla/telemetry/streaming/TestEventsToAmplitude.scala

Previously it wasn't simple to easily and repeatedly execute tests from IDE.
From now on:
* tests are responsible for cleaning up their state (previously it was docker setup script's job)
* generic option for discovering internal IP address is added in docker setup script (useful when one's interface names don't match those listed in script)

Bug 1423340 - Make tests easily runnable from IDE

---

src/main/scala/com/mozilla/telemetry/sinks/HTTPSink.scala
src/test/scala/com/mozilla/telemetry/sinks/TestHTTPSink.scala

This handles:
- Retrying after timeouts
- Retrying after server errors
- Logging on failures
docs here on response codes: https://amplitude.zendesk.com/hc/en-us/articles/204771828#http-status-codes-retrying-failed-requests
Note that this change does not include dealing with too-large payloads (response 413) since at this point we're nowhere near that number for any payload. Bug 1449092 will handle that.

Make HTTP sink more resilient to errors

---

src/main/scala/com/mozilla/telemetry/streaming/ErrorAggregator.scala
src/test/scala/com/mozilla/telemetry/streaming/TestErrorAggregator.scala
src/test/scala/com/mozilla/telemetry/streaming/TestExperimentsErrorAggregator.scala

Changes:
* small refactor in ErrorAggregates (watermark application is unconditional, see commit message for explanation), resulting in a little cleaner method signatures
* temporary test directories are cleaned before and after tests, making local development less prone to problems caused by leftover data

V2 refactor

---

src/main/scala/com/mozilla/telemetry/streaming/ErrorAggregator.scala

Coalescing to 1 partition constrains all aggregations to one node, which eventually causes OOMs on production workloads.

Use repartition instead of coalesce in streaming job

---

src/main/scala/com/mozilla/telemetry/pings/package.scala
src/main/scala/com/mozilla/telemetry/streaming/ErrorAggregator.scala
src/test/scala/com/mozilla/telemetry/TestUtils.scala
src/test/scala/com/mozilla/telemetry/streaming/TestErrorAggregator.scala

This adds `startup_crashes` metric, based on Error Ping's `payload.metadata.StartupCrash`.

Bug 1434378 - Track startup crashes

---

src/main/scala/com/mozilla/telemetry/streaming/ExperimentsErrorAggregator.scala
src/test/scala/com/mozilla/telemetry/streaming/TestExperimentsErrorAggregator.scala

Previous PR (https://github.com/mozilla/telemetry-streaming/pull/113) missed experiment_error_aggregates.

Bug 1434378 - Track startup crashes in experiment_error_aggregates

---

src/main/scala/com/mozilla/telemetry/pings/FocusEvent.scala

If the setting is missing, it is simply discarded by the `compact` call:
```
> compact(render(("x" -> None: Option[String]) ~ ("y" -> "hello": Option[String])))
res1: String = {"y":"hello"}
```

Make Focus-Event settings optional

---

src/main/scala/com/mozilla/telemetry/pings/package.scala
src/test/scala/com/mozilla/telemetry/TestUtils.scala
src/test/scala/com/mozilla/telemetry/streaming/TestErrorAggregator.scala

This fixes `normalizedBuildId`, which used incorrect date format.

Use proper submission date format in normalized build_id extraction

---

build.sbt
src/main/resources/log4j.properties
src/main/scala/com/mozilla/telemetry/streaming/ErrorAggregator.scala
src/main/scala/com/mozilla/telemetry/streaming/ExperimentsErrorAggregator.scala
src/test/scala/com/mozilla/telemetry/streaming/TestErrorAggregator.scala
src/test/scala/com/mozilla/telemetry/streaming/TestExperimentsErrorAggregator.scala

Also in separate commit: bump Spark version to 2.3.0 in order to use dynamic partition overwrite.

Bug 1393144 - Use submission_date_s3 for partitioning error_aggregates

---

build.sbt
src/main/scala/com/mozilla/telemetry/streaming/ErrorAggregator.scala
src/main/scala/com/mozilla/telemetry/streaming/ExperimentsErrorAggregator.scala
src/test/scala/com/mozilla/telemetry/streaming/TestErrorAggregator.scala
src/test/scala/com/mozilla/telemetry/streaming/TestExperimentsErrorAggregator.scala

Following fields are removed since they're not used and not needed in v2:
* `subsession_count`
* `first_subsession_count`
* `input_event_response_coalesced_ms_main_above_150`
* `input_event_response_coalesced_ms_main_above_250`
* `input_event_response_coalesced_ms_main_above_2500`
* `input_event_response_coalesced_ms_content_above_150`
* `input_event_response_coalesced_ms_content_above_250`
* `input_event_response_coalesced_ms_content_above_2500`
* `ghost_windows_main_above_1`
* `ghost_windows_content_above_1`
* `gc_max_pause_ms_2_main_above_150`
* `gc_max_pause_ms_2_main_above_250`
* `gc_max_pause_ms_2_main_above_2500`
* `gc_max_pause_ms_2_content_above_150`
* `gc_max_pause_ms_2_content_above_250`
* `gc_max_pause_ms_2_content_above_2500`
* `cycle_collector_max_pause_main_above_150`
* …

Bug 1454047 - Remove unused metrics from error_aggregates

---

src/main/scala/com/mozilla/telemetry/pings/package.scala
src/main/scala/com/mozilla/telemetry/streaming/ErrorAggregator.scala
src/test/scala/com/mozilla/telemetry/TestUtils.scala
src/test/scala/com/mozilla/telemetry/streaming/TestErrorAggregator.scala

If `displayVersion` is not available, we'll fall back to `meta.appVersion`.

Bug 1461773 - Use core pings's `displayVersion` field for `display_version` dimension

---

build.sbt
src/main/scala/com/mozilla/telemetry/pings/MainPing.scala
src/main/scala/com/mozilla/telemetry/pings/Ping.scala
src/main/scala/com/mozilla/telemetry/streaming/ExperimentEnrollmentsAggregator.scala
src/test/scala/com/mozilla/telemetry/TestUtils.scala
src/test/scala/com/mozilla/telemetry/streaming/ExperimentEnrollmentsAggregatorTest.scala
src/test/scala/com/mozilla/telemetry/streaming/TestErrorAggregator.scala
src/test/scala/com/mozilla/telemetry/streaming/TestEventsToAmplitude.scala
src/test/scala/com/mozilla/telemetry/streaming/TestExperimentsErrorAggregator.scala

This adds job for aggregating experiment uptake events.
Since `spark-testing-base` was introduced for testing this job, couple of existing tests had to be migrated to this library to avoid runtime issues.

Bug 1465442 - Add experiment enrollment event aggregator

---

src/main/scala/com/mozilla/telemetry/streaming/ErrorAggregator.scala
src/main/scala/com/mozilla/telemetry/streaming/EventsToAmplitude.scala
src/main/scala/com/mozilla/telemetry/streaming/ExperimentEnrollmentsAggregator.scala
src/main/scala/com/mozilla/telemetry/streaming/ExperimentsErrorAggregator.scala
src/main/scala/com/mozilla/telemetry/streaming/StreamingJobBase.scala
src/test/scala/com/mozilla/telemetry/streaming/StreamingJobBaseTest.scala
src/test/scala/com/mozilla/telemetry/streaming/TestErrorAggregator.scala
src/test/scala/com/mozilla/telemetry/streaming/TestEventsToAmplitude.scala
src/test/scala/com/mozilla/telemetry/streaming/TestExperimentsErrorAggregator.scala

Spark suffixes couple of `spark.streaming` metrics with streaming query names. Datadog, which we're using for collecting metrics, doesn't allow using wildcards in metric paths for templating graphs. This makes creating templated dashboards for streaming jobs impossible if each of them uses different query name.
As a workaround, Datadog tags should be used for adding dimensions to metrics. Since our jobs run (at least for now) single queries, we can use common query name across all of them and leverage tags for identifying jobs in metrics store.

Use single query name across all jobs for easier monitoring.

---

.travis.yml

Telemetry-batch-view is significantly alterning the deploy.sh
script as that repo moves to CircleCI-based builds in
https://github.com/mozilla/telemetry-batch-view/pull/440
We will move this project to a similar style in a future change,
but for now we're pinning the deploy.sh url to the last tag
of t-b-v with Travis-based deploys.

Pin an explicit version of the deploy.sh script to fetch

---

src/main/resources/log4j.properties
src/test/scala/com/mozilla/telemetry/sinks/TestHTTPSink.scala

I left this warning in place because it looks something that shouldn't be silenced in prod
<pre>
18/05/29 13:43:37 WARN SharedState: URL.setURLStreamHandlerFactory failed to set FsUrlStreamHandlerFactory
</pre>

Bug 1464191 - Silence logs that are too verbose

---

src/main/scala/com/mozilla/telemetry/pings/EventPing.scala
src/main/scala/com/mozilla/telemetry/streaming/EventPingEvents.scala
src/test/scala/com/mozilla/telemetry/TestUtils.scala
src/test/scala/com/mozilla/telemetry/pings/TestEventPing.scala
src/test/scala/com/mozilla/telemetry/streaming/TestEventPingEvents.scala

The Events ping landed a few days ago in nightly, so this job writes the events coming in over the event pings into the `events` dataset (which is already partitioned by docType, how convenient!) This will be paired with an update to the main ping events job in telemetry-batch-view that updates the schema to be in line with the one laid out here (but the schema changes should be backwards-compatible so I'm opting not to bump the version.)
I plan to schedule this as a batch job for now but the job ended up here instead of in telemetry-batch-view since what I'm aiming for in Q3 is to create a streaming job that takes in both main and event pings, explodes out the events and publishes them in to a new kafka topic to be consumed by both the job that writes out the events dataset as well as …

Event ping events in events dataset

---

build.sbt
src/main/scala/com/mozilla/telemetry/pings/MainPing.scala
src/main/scala/com/mozilla/telemetry/pings/Ping.scala
src/main/scala/com/mozilla/telemetry/streaming/ErrorAggregator.scala
src/main/scala/com/mozilla/telemetry/streaming/EventsToAmplitude.scala

This fixes all remaining compiler warnings and requires warning-free builds from now on.

Enforce warning-free compilation

---

src/main/resources/schemas/devtoolsConfigFile.json
src/main/resources/schemas/schemaFileSchema.json
src/main/scala/com/mozilla/telemetry/pings/EventPing.scala
src/main/scala/com/mozilla/telemetry/pings/MainPing.scala
src/main/scala/com/mozilla/telemetry/pings/Ping.scala
src/main/scala/com/mozilla/telemetry/streaming/EventsToAmplitude.scala
src/test/resources/testMainPingConfigFile.json
src/test/scala/com/mozilla/telemetry/streaming/TestEventsToAmplitude.scala

Requesting review from @jklukas since he'll be looking into adding the schema file and running the job to take care of Savant events
This PR does two things:
- Add support for the Event ping in EventsToAmplitude
- Add the concept of a sessionIdOffset to the amplitude event schema, since devtools needs a separate session_id for each time the devtools toolbox was opened (including when there are multiple toolboxes open) to really make sense of their event data

Devtools amplitude update

---

src/test/scala/com/mozilla/telemetry/pings/EventPingTest.scala
src/test/scala/com/mozilla/telemetry/pings/FocusEventPingTest.scala
src/test/scala/com/mozilla/telemetry/pings/PingsTest.scala
src/test/scala/com/mozilla/telemetry/sinks/HTTPSinkTest.scala
src/test/scala/com/mozilla/telemetry/streaming/ErrorAggregatorTest.scala
src/test/scala/com/mozilla/telemetry/streaming/EventPingEventsTest.scala
src/test/scala/com/mozilla/telemetry/streaming/EventsToAmplitudeTest.scala
src/test/scala/com/mozilla/telemetry/streaming/ExperimentsErrorAggregatorTest.scala

This makes test naming consistent in this repository by renaming some test classes to use ".+Test" pattern, similar as in https://github.com/mozilla/telemetry-batch-view

Use consistent naming across test classes

---

src/main/scala/com/mozilla/telemetry/streaming/ErrorAggregator.scala

[bug link](https://bugzilla.mozilla.org/show_bug.cgi?id=1476789)
The `experiments_error_aggregates` job in airflow is a dependency of the `experiments_aggregates` job in the `main_summary` DAG. I'm currently setting the channel to nightly in the MainSummaryView when the deploy environment is `dev`. 
This PR exposes an option to set a channel to filter in the options. I also set the `minPartitions` option in `Dataset.records` so that the job finishes in a reasonable amount of time on a single machine. I think this should work out on the current production settings.
In order to avoid spilling, the partitions should be roughly this size: 
`size(partition) <= memory * spark.memory.fraction / spark.default.parallelism`
or roughly `~30GB * 0.6 / 32 <= 562.5 MB` with c3.x4large nodes.
With our …

Bug 1476789 - Add channel option to ErrorAggregator

---

configs/desktop_savant_events_schemas.json
configs/focus_android_events_schemas.json
src/main/resources/schemas/devtoolsConfigFile.json
src/main/resources/schemas/schemaFileSchema.json
src/main/resources/schemas/simpleFocusConfigFile.json
src/main/scala/com/mozilla/telemetry/pings/Ping.scala
src/main/scala/com/mozilla/telemetry/streaming/EventsToAmplitude.scala
src/test/resources/testConfigFile.json
src/test/resources/testMainPingConfigFile.json
src/test/scala/com/mozilla/telemetry/pings/FocusEventPingTest.scala
src/test/scala/com/mozilla/telemetry/streaming/EventsToAmplitudeTest.scala

This adds the JSON file to support Savant event mappings and adds a few new features to support those mappings.
First, we now support literal fields. Values enclosed in single quotes will output the literal value rather than looking up the property in the event.
Second, we now support dataset sources other than "telemetry".

Bug 1474987 Add pipeline for Savant events to Amplitude

---

src/main/scala/com/mozilla/telemetry/streaming/CrashPingStreamingBase.scala

I just realized buildId is the only way to differentiate nightly 😖

Add buildId to crash ping tags

---

src/main/scala/com/mozilla/telemetry/pings/MainPing.scala
src/test/scala/com/mozilla/telemetry/TestUtils.scala
src/test/scala/com/mozilla/telemetry/streaming/EventsToAmplitudeTest.scala

The simpleMeasurement version of activeTicks is sometimes inflated.
We will need to backfill the Savant project in Amplitude using this updated logic.

Bug 1482924 Use active_ticks scalar rather than simpleMeasurement

---

configs/desktop_savant_events_schemas.json

As discussed in https://bugzilla.mozilla.org/show_bug.cgi?id=1482924
we want to backfill just session split events in order to pick up the
new active-ticks logic. We can only accomplish that in Amplitude
by sending events with a different name.
Once this is merged, I'll proceed with backfilling.

Bug 1482924 Change session split event name for backfill

---

configs/desktop_savant_events_schemas.json
src/main/scala/com/mozilla/telemetry/pings/Ping.scala

The "Meta - session split v2" events we backfilled were
rejected for recent days due to having identical insert_id
to the v1 events.
We change the logic so that future event name changes will
not get deduplicated, and we bump the session split event name again.
This time, I'll backfill and verify _before_ merging the PR in case
we encounter another hiccup.

Bug 1482924 Add event name to insert_id

---

configs/focus_android_events_schemas.json
src/main/resources/schemas/schemaFileSchema.json
src/main/scala/com/mozilla/telemetry/streaming/EventsToAmplitude.scala
src/test/scala/com/mozilla/telemetry/streaming/EventsToAmplitudeTest.scala

As it turns out, we were never checking the config validation output in our validation code -- fixing this uncovered a bunch of issues with the meta-schema drifting over time from what was in the code, and sundry small issues in the config files that shouldn't have code impact.
I highly suggest using the `?w=1` trick at the end of the PR's url to hide whitespace changes

Bug 1471368: Update meta-schema file and config files

---

src/main/scala/com/mozilla/telemetry/pings/Ping.scala
src/main/scala/com/mozilla/telemetry/sinks/AmplitudeBatchHttpSink.scala
src/main/scala/com/mozilla/telemetry/sinks/HttpSink.scala
src/main/scala/com/mozilla/telemetry/streaming/EventsToAmplitude.scala
src/test/scala/com/mozilla/telemetry/sinks/AmplitudeBatchHttpSinkTest.scala
src/test/scala/com/mozilla/telemetry/streaming/EventsToAmplitudeTest.scala

As discussed in https://bugzilla.mozilla.org/show_bug.cgi?id=1484819 we can likely achieve significantly higher throughput by using the /batch endpoint.
This PR also adds partitioning by client ID, so that each partition contains a subset of IDs. Amplitude throttles per device_id, so this keeps the effects of a throttled device more localized.
I've tested this code on ATMO by sending some events via the batch endpoint to the Savant_Dev project, and received zero errors while doing so.
Note that jobs still pass in the endpoint to use, so merging this change should have no effect on how currently configured jobs run. To switch Airflow jobs to the /batch endpoint will require a PR to telemetry-airflow.

Bug 1484819 Support Amplitude /batch endpoint; partition data

---

build.sbt
project/build.properties
src/main/scala/org/apache/spark/metrics/source/custom/AccumulatorMetricsSource.scala
src/test/scala/org/apache/spark/metrics/source/custom/AccumulatorMetricsSourceTest.scala

This adds simple Spark metrics source based on accumulators.
Because it's leveraging internal API, source is added in `org.apache.spark`.

Bug 1485583 - Add accumulator-based metrics source

---

configs/devtools_events_schemas.json

The devtools team would like to start playing with this data now that 63 is on beta/aurora

Add beta and aurora to devtools e2a config

---

src/main/scala/com/mozilla/telemetry/streaming/CrashesToInflux.scala
src/main/scala/com/mozilla/telemetry/streaming/CrashesToOpenTsdb.scala
src/main/scala/com/mozilla/telemetry/streaming/ErrorAggregator.scala
src/main/scala/com/mozilla/telemetry/streaming/EventPingEvents.scala
src/main/scala/com/mozilla/telemetry/streaming/EventsToAmplitude.scala
src/main/scala/com/mozilla/telemetry/streaming/ExperimentEnrollmentsAggregator.scala
src/main/scala/com/mozilla/telemetry/streaming/ExperimentEnrollmentsToTestTube.scala
src/main/scala/com/mozilla/telemetry/streaming/ExperimentsEnrollmentsToDatadog.scala
src/main/scala/com/mozilla/telemetry/streaming/ExperimentsErrorAggregator.scala
src/main/scala/com/mozilla/telemetry/streaming/FederatedLearningSearchOptimizer.scala
src/main/scala/com/mozilla/telemetry/streaming/StreamingJobBase.scala
src/test/scala/com/mozilla/telemetry/streaming/CrashPingStreamingBaseTest.scala
src/test/scala/com/mozilla/telemetry/streaming/StreamingJobBaseTest.scala

As discussed as we were looking to remediate the streaming jobs contributing to the kafka outage -- Adds a JobName value to the streaming base class and sets the default checkpoint using this value.

Default to a per-job streaming checkpoint location

---

src/main/scala/com/mozilla/telemetry/pings/Ping.scala
src/test/scala/com/mozilla/telemetry/pings/PingsTest.scala

This fixes Event Ping Events job failing with null pointer exception.
The reason was:
`OS#normalizedVersion` could return null if `version` string was empty (https://github.com/mozilla/telemetry-streaming/pull/188/files#diff-be261a172bbe8ba3137a937df3a3f5c6R199).
This caused `Ping#getOsVersion` to return `Some(null)` (https://github.com/mozilla/telemetry-streaming/pull/188/files#diff-be261a172bbe8ba3137a937df3a3f5c6R266).
Test runs (3rd one is with this fix applied): https://dbc-caf9527b-e073.cloud.databricks.com/#job/756

Bug 1509120 - Fix NullPointerException on OS version normalization

---

configs/devtools_release_schemas.json
src/main/scala/com/mozilla/telemetry/streaming/EventsToAmplitude.scala

* Only look for events in the events ping
* Add a partition multiplier option (sped up the filter/explode stage significantly in manual runs)

E2A updates for devtools release job

---

src/main/scala/com/mozilla/telemetry/streaming/FederatedLearningSearchOptimizer.scala
src/test/scala/com/mozilla/telemetry/TestUtils.scala
src/test/scala/com/mozilla/telemetry/streaming/FederatedLearningSearchOptimizerTest.scala

The Federated Learning v2 experiment needs to have an extra parameter
passed in to distinguish between the 4 different models that need to be
trained.
The filter to select relevant pings has been updatd.
Extra test case added demonstrating filtering the aggregation step by
using the variation name to drop ignorable pings.

Patch to add a modelBranch argument to the Federated Learning v2 study

---

src/main/scala/com/mozilla/telemetry/streaming/FederatedLearningSearchOptimizer.scala

This enables skipping over data loss for the federated learning streaming jobs.
See bug https://bugzilla.mozilla.org/show_bug.cgi?id=1540562

added option for failOnDataLoss to be false to skip over aged out data

---

src/main/scala/com/mozilla/telemetry/pings/EventPing.scala
src/test/scala/com/mozilla/telemetry/TestUtils.scala
src/test/scala/com/mozilla/telemetry/streaming/ExperimentEnrollmentsAggregatorTest.scala

Enrollment monitoring for the FX quantum bar HTML (vs XUL) experiment was broken -- turns out it was because normandy events moved to the parent process in 67, and the experiment was running in Nightly ([bug for that change](https://bugzilla.mozilla.org/show_bug.cgi?id=1443560))
`EventPing.getNormandyEvents` now looks for normandy pings in all events. I left the MainPing as-is since events in the Main Ping should be considered legacy at this point.

Bug 1538793: look for Normandy events from all processes

---

configs/devtools_prerelease_schemas.json
configs/devtools_release_schemas.json

The Devtools team has instrumented new events for about:debugging and would like them in amplitude -- I've updated the configs for release and prerelease with them and tested in the devtools_dev project and all the events & properties shipped correctly as far as I can tell

Bug 1542349: Add new about:debugging devtools events to e2a configs

---

configs/devtools_prerelease_schemas.json
configs/devtools_release_schemas.json

Adds runtime_os and runtime_version extras described in https://bugzilla.mozilla.org/show_bug.cgi?id=1530997 to the e2a configs for devtools.

Bug 1530997 - Ship new runtime_connected extras to Amplitude
