- .travis.yml
- build.sbt
- src/main/scala/com/mozilla/telemetry/streaming/ErrorAggregator.scala
- src/test/scala/com/mozilla/telemetry/streaming/TestAggregator.scala
This is based on top of https://github.com/vitillo/telemetry-streaming/pull/1. Please at the last commit only
> Add error counts to CrashAggregator output

- build.sbt
> Don't run tests when running sbt assembly

- src/main/scala/com/mozilla/telemetry/streaming/ErrorAggregator.scala
> Increase kafka consumers cache size

- src/main/resources/log4j.properties
> Add log4j configuration file

- build.sbt
- src/main/scala/com/mozilla/telemetry/streaming/ErrorAggregator.scala
Worked on a cluster. We don't usually have tests for these kind of code paths though.
> Add options to run in batch mode

- src/main/scala/com/mozilla/telemetry/pings/package.scala
- src/main/scala/com/mozilla/telemetry/streaming/ErrorAggregator.scala
- src/test/scala/com/mozilla/telemetry/streaming/TestAggregator.scala
- src/test/scala/com/mozilla/telemetry/streaming/TestPings.scala
- src/test/scala/com/mozilla/telemetry/streaming/TestUtils.scala
This is the first measure that requires a non-sum aggregation. I added
a map to define which columns require which aggregation. If a column is
not listed there, it falls back to a sum().
> Add mean firstPaint

- src/main/scala/com/mozilla/telemetry/pings/package.scala
- src/test/scala/com/mozilla/telemetry/streaming/TestAggregator.scala
- src/test/scala/com/mozilla/telemetry/streaming/TestUtils.scala
Add test for pref flip experiments which required a parsing update.
> Add a test for new style experiments

- src/main/scala/com/mozilla/telemetry/streaming/ErrorAggregator.scala
I can't prove to you that this fails with a test *yet*, but soon!
> Fix runtime error

- src/main/scala/com/mozilla/telemetry/streaming/ErrorAggregator.scala
> Set number of files per partition

- src/main/scala/com/mozilla/telemetry/streaming/ErrorAggregator.scala
- src/test/scala/com/mozilla/telemetry/streaming/TestErrorAggregator.scala
We found out that a handful of the HLL fields introduced to handle session-based counts and filtered client counts killed the dimension of the output parquet files. 
See https://bugzilla.mozilla.org/show_bug.cgi?id=1388351 for more context.
> Remove session-based counts and filtered client counts

- .travis.yml
- build.sbt
- docker/docker-compose.yml
- docker_setup.sh
- project/plugins.sbt
- src/main/scala/com/mozilla/telemetry/streaming/ErrorAggregator.scala
- src/test/scala/com/mozilla/telemetry/TestUtils.scala
- src/test/scala/com/mozilla/telemetry/streaming/TestErrorAggregator.scala
Alright, this should make it easy to try out new changes with spark-streaming!
This also shows the bug I mentioned.
> Add integration tests

- src/main/scala/com/mozilla/telemetry/streaming/ErrorAggregator.scala
- src/main/scala/com/mozilla/telemetry/streaming/ExperimentsErrorAggregator.scala
- src/main/scala/com/mozilla/telemetry/timeseries/package.scala
- src/test/scala/com/mozilla/telemetry/streaming/TestErrorAggregator.scala
- src/test/scala/com/mozilla/telemetry/streaming/TestExperimentsErrorAggregator.scala
This is exactly error_aggregates, but with a subset of
dimensions and statistics.
The only other changes made were to enable missing schema elements.
> Add experiments_aggregates job

- src/main/scala/com/mozilla/telemetry/streaming/ErrorAggregator.scala
- src/main/scala/com/mozilla/telemetry/streaming/ExperimentsErrorAggregator.scala
- src/test/scala/com/mozilla/telemetry/streaming/TestErrorAggregator.scala
- src/test/scala/com/mozilla/telemetry/streaming/TestExperimentsErrorAggregator.scala
Using classes was causing all kind of serialization issues. This removes those in favor of altering `var`s in the `ErrorAggregator` object.
> Remove classes in favor of objects

- README.md
> Some docs about how to invoke unit tests

- build.sbt
- src/main/resources/schemas/schemaFileSchema.json
- src/main/resources/schemas/simpleFocusConfigFile.json
- src/main/scala/com/mozilla/telemetry/pings/FocusEvent.scala
- src/main/scala/com/mozilla/telemetry/pings/package.scala
- src/main/scala/com/mozilla/telemetry/streaming/EventsToAmplitude.scala
- src/test/resources/testConfigFile.json
- src/test/scala/com/mozilla/telemetry/TestUtils.scala
- src/test/scala/com/mozilla/telemetry/pings/TestFocusEventPing.scala
- src/test/scala/com/mozilla/telemetry/streaming/TestEventsToAmplitude.scala
Basically, this introduces a config JSON, which includes JSON schemas for all of the events that we're interested in sending to Amplitude. This schema is matched against all of the events in the pings (which kind of sucks).
I have used this to load 2 months of data into Ampltidue, using the following Config:
```
{
"eventGroupName": "Focus",
"filters": {
"docType": [
"focus-event"
],
"appName": [
"Focus",
"OTHER"
],
"os": [
"Android"
]
},
"events": [
{
"name": "App Open",
"description": "User opening the app",
"schema": {
"$schema": "http://json-schema.org/schema#",
"type": "object",
"properties": {
"timestamp": {
"type": "number",
"minimum": 0
},
"category": {
"type": "string",
"enum": [ "action" ]
},
"method": {
"type": "string",
"enum": [ "foreground" ]
},
"object": {
"type": "string", …
```
> Events schemas

- build.sbt
- project/build.properties
- project/plugins.sbt
* Bump sbt to v1.1.1
* Shade Protobuf for running on Databricks
* Reduce Kafka dependency scope to test
> Update sbt build configuration

- src/main/scala/com/mozilla/telemetry/streaming/EventsToAmplitude.scala
- src/test/scala/com/mozilla/telemetry/streaming/TestEventsToAmplitude.scala
This is done automatically by scalaj HTTP.
> Remove URL Encoding

- src/main/scala/com/mozilla/telemetry/sinks/HTTPSink.scala
- src/test/scala/com/mozilla/telemetry/sinks/TestHTTPSink.scala
> Fix extra request attempt in HTTPSink

- src/main/scala/com/mozilla/telemetry/sinks/HTTPSink.scala
- src/test/scala/com/mozilla/telemetry/sinks/TestHTTPSink.scala
- src/test/scala/com/mozilla/telemetry/streaming/TestEventsToAmplitude.scala
GET requests were returning 414 errors, which do not affect
POST requests.
> Use POST not GET in HttpSink

- src/main/scala/com/mozilla/telemetry/streaming/EventsToAmplitude.scala
Previously, it was using the algorithm of "Fill partitions
with files until full". It was causing the job extreme delays.
This changes to "N equally sized partitions", which runs in
a decent amount of time.
@acmiyaguchi tagging you for review because of our recent discussion on this algorithm.
> Make set number of partitions for EventsToAmplitude

- src/main/scala/com/mozilla/telemetry/streaming/ExperimentEnrollmentsAggregator.scala
This introduces a temporary fix for parse error that occurred in production.
> Handle docType parse errors in experiments enrollment aggregator

- build.sbt
- src/main/scala/com/mozilla/telemetry/pings/Ping.scala
- src/test/scala/com/mozilla/telemetry/streaming/TestEventsToAmplitude.scala
Also address a style warning.
It's not obvious to me how master got into a state where tests won't compile.
> Fix tests that are failing on master

- src/main/scala/com/mozilla/telemetry/sinks/BatchHttpSink.scala
- src/main/scala/com/mozilla/telemetry/streaming/CrashesToInflux.scala
- src/test/scala/com/mozilla/telemetry/sinks/BatchHTTPSinkTest.scala
- src/test/scala/com/mozilla/telemetry/streaming/CrashesToInfluxTest.scala
Sends crashes as string to an http server
> Streaming to influx

- src/main/scala/com/mozilla/telemetry/learning/federated/FederatedLearningRPropOptimizer.scala
- src/main/scala/com/mozilla/telemetry/learning/federated/FederatedLearningSearchOptimizerS3Sink.scala
- src/main/scala/com/mozilla/telemetry/streaming/FederatedLearningSearchOptimizer.scala
I think this hits all the logs we'd want (besides the per-branch monitors, which we'll do in hindsight)
> Add logs to federated learning optimizer

- src/main/scala/com/mozilla/telemetry/streaming/ExperimentEnrollmentsAggregator.scala
- src/test/scala/com/mozilla/telemetry/streaming/ExperimentEnrollmentsAggregatorTest.scala
This adds support for event pings in old experiment enrollments job.
> Bug 1471659 - Read event pings in experiment enrollments job

- src/main/scala/com/mozilla/telemetry/monitoring/DogStatsDMetric.scala
- src/main/scala/com/mozilla/telemetry/sinks/DogStatsDMetricSink.scala
- src/main/scala/com/mozilla/telemetry/streaming/ExperimentsEnrollmentsToDatadog.scala
- src/test/scala/com/mozilla/telemetry/monitoring/DogStatsDCounterTest.scala
- src/test/scala/com/mozilla/telemetry/sinks/DogStatsDCounterSinkTest.scala
WIP while I make sure this new version works in databricks
> Add experiment enrollments to datadog job

- src/main/scala/com/mozilla/telemetry/sinks/HttpSink.scala
- src/main/scala/com/mozilla/telemetry/streaming/EventsToAmplitude.scala
- src/test/scala/com/mozilla/telemetry/sinks/HttpSinkMetricsTest.scala
- src/test/scala/com/mozilla/telemetry/sinks/HttpSinkTest.scala
- src/test/scala/org/apache/spark/metrics/source/custom/AccumulatorMetricsSourceTest.scala
Factors some test fixtures out of HttpSinkTest and AccumulatorMetricsSourceTest in order to reuse them in the new test for HttpSink.Metrics
> Bug 1465974 Add metrics reporting to HttpSink

- .circleci/config.yml
See related changes in t-b-v:
https://github.com/mozilla/telemetry-batch-view/pull/487
> Bug 1498309 Refactor CircleCI config and use cache for assembly

- README.md
See related documentation changes in https://github.com/mozilla/emr-bootstrap-spark/pull/656
> Document deployment dependencies

- configs/fennec_ios_events_schemas.json
- src/main/scala/com/mozilla/telemetry/pings/MobileEvent.scala
- src/main/scala/com/mozilla/telemetry/pings/Ping.scala
- src/test/scala/com/mozilla/telemetry/streaming/EventsToAmplitudeTest.scala
This adds iOS Fennec/Amplitude integration
> Add iOS event schema and MobileEventPing

- configs/rocket_android_events_schemas.json
this is to update telemetry events for firefox lite v1.5.0
> update telemetry events for v1.5.0

- configs/rocket_android_events_schemas.json
telemetry event update for FirefoxLite 4c4ee797
> telemetry event update for FirefoxLite v1.6.0

- configs/fire_tv_events_schemas.json
- src/main/scala/com/mozilla/telemetry/pings/FireTvEventPing.scala
- src/main/scala/com/mozilla/telemetry/pings/Ping.scala
- src/test/scala/com/mozilla/telemetry/streaming/EventsToAmplitudeTest.scala
This follows the format of previous new pings. I kept device and arch optional, since they are included in the schema.
> Fire TV Events to Amplitude

- configs/rocket_android_events_schemas.json
> Firefox Lite v1.8.0

- configs/devtools_prerelease_schemas.json
- configs/devtools_release_schemas.json
Added a bunch more devtools events. I'm hoping the next PR for devtools amplitude will be figuring out how to ship all of this over automatically via a bigquery query and csv export
> Bug 1566996: Add more devtools events
